name: Build/Test/Deploy
on:
  push:
    branches:
      - feature/github_actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout_Repo
      uses: actions/checkout@v2
      
    - name: Install_UV
      uses: astral-sh/setup-uv@v7

    - name: Steup_Python
      uses: actions/setup-python@v6.2.0
      with:
        python-version-file: .python-version
